### ISSUE TITLE
Textbox with prefix has inconsistent styling when readonly

### ISSUE THREAD

**Issue by yngndrw-sage** [Sage/carbon#1876]
If you have a Textbox which is both readonly and has a prefix, a border is applied which is different to be behaviour when the Textbox does not have a prefix.

Readonly adds styles which remove the border:
```css
.common-input--readonly .common-input__input {
    background-color: transparent;
    border: none;
}
````

Prefix adds additional styles which override the readonly styles and re-add the border, as they are more selective:
```css
.carbon-fieldset .common-input--readonly .common-input__input {
    border: 1px solid #C4C6CA;
}
```
