### ISSUE TITLE
Button types and colours

### ISSUE THREAD

**Issue by SeanArmstrong** [Sage/carbon#796]
Button allows a prop of type to be passed.
Currently this is limited to `primary` `secondary` `red` and `green`.

The way of working keeps things consistent but give no scope for customisation. Instead I think we should define two button type `primary` and `secondary`.

A `primary` button has a full background color and secondary color text.
A `secondary` button has coloured text and border but a white/transparent background

The user could then define a colour set with a given name as a css class `carbon-button__colour-set--red` which would get added by the colourSet prop (default would be blue and white)

In their css they would have to add some sort of set e.g.

``` css
.carbon-button__colour-set--red {
  background-color: 'red'
  color: 'white'

  &:hover {
    background-color: 'red2'
  }
}
```
